language: python

env:
  - TOX_ENV=py34-django18
  - TOX_ENV=py33-django18
  - TOX_ENV=py32-django18
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django17
  - TOX_ENV=py33-django17
  - TOX_ENV=py32-django17
  - TOX_ENV=py27-django17
  - TOX_ENV=py34-django16
  - TOX_ENV=py33-django16
  - TOX_ENV=py32-django16
  - TOX_ENV=py27-django16
  - TOX_ENV=coverage

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

matrix:
    allow_failures:
        - TOX_ENV=py33-django17

sudo: false
