language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script:
  - django-admin.py test djangomaat
